const $=s=>document.querySelector(s),api=(u,o={})=>fetch(u,{headers:{'Content-Type':'application/json',...(o.headers||{})},...o}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.error);return b});
function countryFlag(code){let cc=(code||'').toUpperCase();return /^[A-Z]{2}$/.test(cc)?`<img src="https://flagcdn.com/w40/${cc.toLowerCase()}.png" width="20" height="15" alt="${cc}"> ${cc}`:'\u672a\u77e5'}
function rate(value){let n=Number(value)||0,units=['B/s','KB/s','MB/s','GB/s'],i=0;while(n>=1024&&i<3){n/=1024;i++}return (n>=10?n.toFixed(0):n.toFixed(1))+' '+units[i]}
function networkChart(canvas,history=[]){let w=270,h=56,d=devicePixelRatio||1,c=canvas.getContext('2d');canvas.width=w*d;canvas.height=h*d;c.scale(d,d);let samples=history.slice(-30),peak=Math.max(1,...samples.flatMap(x=>[Number(x.rx)||0,Number(x.tx)||0]));[['rx','#38bdf8'],['tx','#10b981']].forEach(([key,color])=>{c.beginPath();samples.forEach((x,i)=>{let px=samples.length>1?i*w/(samples.length-1):0,py=h-(Number(x[key])||0)/peak*(h-4)-2;i?c.lineTo(px,py):c.moveTo(px,py)});c.strokeStyle=color;c.lineWidth=2;c.stroke()})}
function duration(s){s=Number(s)||0;if(s>=86400)return Math.floor(s/86400)+'\u5929';let h=Math.floor(s/3600),m=Math.floor(s%3600/60);return `${h}\u5c0f\u65f6 ${m}\u5206`}
function gauge(canvas,v){let c=canvas.getContext('2d'),d=devicePixelRatio||1;c.canvas.width=c.canvas.height=62*d;c.scale(d,d);c.lineWidth=6;c.strokeStyle=getComputedStyle(document.body).getPropertyValue('--line');c.beginPath();c.arc(31,31,25,-1.57,4.71);c.stroke();c.strokeStyle=v>80?'#f97316':'#10b981';c.beginPath();c.arc(31,31,25,-1.57,4.71*v/100-1.57);c.stroke()}
function render(nodes){$('#online').textContent=nodes.filter(n=>n.online).length;let box=$('#nodes');box.innerHTML='';nodes.forEach(n=>{let e=$('#node-card').content.cloneNode(true),ms=[n.cpu,n.memory,n.disk];e.querySelector('strong').textContent=n.name||'\u672a\u547d\u540d\u8282\u70b9';e.querySelector('i').className=n.online?'':'offline';e.querySelector('.status').textContent=n.online?'\u5728\u7ebf':'\u79bb\u7ebf';e.querySelector('.ip').textContent='IP '+n.ip;e.querySelector('.loc').innerHTML=countryFlag(n.country);e.querySelector('.os').textContent=n.os||'\u7cfb\u7edf\u672a\u77e5';e.querySelector('.uptime').textContent='\u8fd0\u884c '+duration(n.uptime);e.querySelector('.net').textContent='\u7f51\u7edc '+rate(n.network_rx)+' \u2193 / '+rate(n.network_tx)+' \u2191';e.querySelectorAll('.metrics div').forEach((x,i)=>{gauge(x.querySelector('canvas'),ms[i]||0);x.querySelector('b').textContent=(ms[i]||0)+'%'});networkChart(e.querySelector('.network-chart canvas'),n.history);box.append(e)})}
async function refresh(){try{render((await api('/api/nodes')).nodes)}catch(e){console.error(e)}}
$('#theme').onclick=()=>{document.body.classList.toggle('dark');$('#theme').textContent=document.body.classList.contains('dark')?'\u6d45\u8272':'\u6df1\u8272';refresh()};$('#layout').onclick=()=>$('#nodes').classList.toggle('list');$('#admin').onclick=()=>{$('#dashboard').hidden=true;$('#admin-panel').hidden=false};$('#back').onclick=()=>{$('#dashboard').hidden=false;$('#admin-panel').hidden=true};
$('#login-btn').onclick=async()=>{try{await api('/api/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});$('#login').hidden=true;$('#manage').hidden=false;loadAdmin()}catch(e){alert(e.message)}};
async function loadAdmin(){let [keys,nodes]=await Promise.all([api('/api/admin/keys'),api('/api/admin/nodes')]),k=$('#keys');k.innerHTML='';keys.keys.forEach(x=>{let r=document.createElement('div');r.className='key';r.innerHTML=`<span><b>${x.label}</b><br><code>${x.key}</code></span><span><button data-use="${x.key}">\u5ba2\u6237\u7aef\u5b89\u88c5</button><button data-del="${x.id}">\u5220\u9664</button></span>`;k.append(r)});k.onclick=async e=>{if(e.target.dataset.use){let s=(await api('/api/install.sh?key='+encodeURIComponent(e.target.dataset.use))).script,bytes=new TextEncoder().encode(s),base64=btoa(String.fromCharCode(...bytes));$('#install').textContent=`echo '${base64}' | base64 -d | bash`}if(e.target.dataset.del){await fetch('/api/admin/keys/'+e.target.dataset.del,{method:'DELETE'});loadAdmin()}};let n=$('#admin-nodes');n.innerHTML='';nodes.nodes.forEach(x=>{let r=document.createElement('div');r.className='edit-node';r.innerHTML=`<input value="${x.name||''}" placeholder="\u8282\u70b9\u540d\u79f0"><input value="${x.country||''}" placeholder="\u56fd\u5bb6\u4ee3\u7801"><button data-save>\u4fdd\u5b58</button><button data-delete>\u5220\u9664\u8282\u70b9</button>`;r.querySelector('[data-save]').onclick=async()=>{let i=r.querySelectorAll('input');await api('/api/admin/nodes',{method:'POST',body:JSON.stringify({id:x.id,name:i[0].value,country:i[1].value})});refresh()};r.querySelector('[data-delete]').onclick=async()=>{if(confirm('\u786e\u5b9a\u5220\u9664\u8be5\u8282\u70b9\u5417\uff1f')){await api('/api/admin/nodes/'+x.id,{method:'DELETE'});refresh();loadAdmin()}};n.append(r)})}
$('#new-key').onclick=async()=>{try{await api('/api/admin/keys',{method:'POST',body:JSON.stringify({label:$('#key-label').value||'\u65b0\u5bc6\u94a5'})});$('#key-label').value='';loadAdmin()}catch(e){alert(e.message)}};refresh();setInterval(refresh,5000);
